# Creating an nxn matrix whose diagonal entries are 1, whose entries touching the diagonals are -2, and whose other values are 0

In [9]:
import numpy as np

# Define the size of the matrix
d = int(input("How big will your nxn matrix be? "))



# Generate the 0 matrix as our starting point
# We choose to use this since as our matrix gets bigger, more of its entries will be 0
matrix = np.zeros((d,d))



# For loop to cycle through every single value in the matrix
for row in range(d):
    for column in range(d):
        
        # If the row and column have the same values, then we are at a diagonal
        if row-column == 0:
            matrix[row][column] = 1
        
        # If their difference is 1, then we are at a value touching the diagonal.
        elif abs(row-column) == 1:
            matrix[row][column] = -2

            
            
#Print our desired matrix
print(matrix)

How big will your nxn matrix be? 10
[[ 1. -2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-2.  1. -2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2.  1. -2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -2.  1. -2.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -2.  1. -2.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -2.  1. -2.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -2.  1. -2.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -2.  1. -2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -2.  1. -2.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -2.  1.]]
