In [1]:
# Graphing functions
def graph_approx(x,y):
    """Inputs our array of inputs x and our approximated array of outputs y to make a graph."""
    import matplotlib.pyplot as plt

    # Plot our values
    plt.plot(x, y, color="black")
    
    # Make cosmetic expectations and display graph
    plt.grid()
    plt.xlabel("X-Axis")
    plt.ylabel("Y-Axis")
    plt.show()
    
def graph_all(x, y_approx, y_exact):
    """Inputs our array of inputs x, our approximated array of outputs y,
    and our known exact y to make a graph."""
    import matplotlib.pyplot as plt
    
    # Plot our values
    plt.plot(x, y_approx, color="black", linestyle="dotted")
    plt.plot(x, y_exact, color="black")
    
    # Make cosmetic expectations and display graph
    plt.grid()
    plt.xlabel("X-Axis")
    plt.ylabel("Y-Axis")
    plt.show()

    
    
    
# Matrix generation functions
def M_matrix(dimension):
    """Used to generate a matrix M that solves M*y(x)=I."""
    import numpy as np
    
    # Generate the 0 matrix as our starting point, make it 1 rows/columns shorter, and make its diagonal -1's
    matrix = np.zeros((dimension-1,dimension-1), dtype = "int8")
    np.fill_diagonal(matrix,int(-1))
    
    
    
    
    # Add a row of 0's to the top and column of 0's to the right
    row = np.zeros((dimension-1,1), dtype = "int8")
    matrix = np.hstack((matrix, row))

    column = np.zeros((1,dimension), dtype = "int8")
    matrix = np.vstack((column, matrix))
    
    # Replace the new diagonals with -2
    np.fill_diagonal(matrix,int(1))
    
    
    
    
    return matrix

def I_matrix():
    """Used to generate an array I that solves M*y(x)=I."""
    import numpy as np

[[ 1  0  0  0  0  0  0  0  0  0]
 [-1  1  0  0  0  0  0  0  0  0]
 [ 0 -1  1  0  0  0  0  0  0  0]
 [ 0  0 -1  1  0  0  0  0  0  0]
 [ 0  0  0 -1  1  0  0  0  0  0]
 [ 0  0  0  0 -1  1  0  0  0  0]
 [ 0  0  0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0 -1  1  0  0]
 [ 0  0  0  0  0  0  0 -1  1  0]
 [ 0  0  0  0  0  0  0  0 -1  1]]


In [ ]:
def ypx_to_kyx(constant, y_initial, x_max, interv_num):
    """With the assumption that the minimum x is x=0 and our initial value is at x=0,
    we input an initial value, a maximum input value, and the number of intervals to
    solve the differential equation y'(x) = k * y(x) with our constant being k.
    
    The EXACT solution to this DE is y(x) = y_0 * e^(kx)."""
    import numpy as np
    from scipy.linalg import lu_factor
    from scipy.linalg import lu_solve
    from time import time
    
    begin = round(time(),2)
    
    # Make our array of x-inputs and our interval width constant
    x_min = 0
    x_val = np.linspace(x_min, x_max, interv_num+1)
    interv_width = (x_max - x_min) / interv_num
    
    
    
    
    # Make our M matrix and I array to assemble the equation M * y(x) = I
    m_matrix = M_matrix()
    i_matrix = I_matrix()
    

    # Make our array of exact y-values and make a graph with our approximated and exact values
    y_exact = y_initial * np.exp(constant * x_val)
    graph_all(x_val, y_val, y_exact)

    
    end = round(time(),2)
    print(f"Finished in {round(end-begin,2)} seconds.")